blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/104devdude/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: View the development documentation
